version: '3'
services:
  quartz-mysql:
    image: 13angs/quartz-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: QRTZ_DB
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: task-scheduler-data
        target: /var/lib/mysql
    networks:
      - task-scheduler-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - task-scheduler-network

networks:
  task-scheduler-network:
    name: task-scheduler-network

volumes:
  task-scheduler-data: