version: '3.8'

services:
  api:
    image: 13angs/task-scheduler:latest
    build:
      context: ../../api
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    
    networks:
      - task-scheduler-network
    
    environment:
      - "ConnectionStrings__Mysql=Data Source=mysql;Port=3306;User ID=root;password=password;Database=QRTZ_DB;"
      - "Scheduler__Secret=${SIG_SECRET}"
      - "RabbitMQ__HostName=${RABBITMQ_HOST}"

networks:
  task-scheduler-network:
    name: task-scheduler-network